const env = {
	GROQ_API_KEY: process.env.GROQ_API_KEY,
	SUPABASE_URL: process.env.SUPABASE_URL,
	SUPABASE_PUBLIC_ANON_KEY: process.env.SUPABASE_PUBLIC_ANON_KEY,
	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
	CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
	NEXT_PUBLIC_STRIPE_PUBLIC_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY,
	STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
	FRONTEND_URL: process.env.FRONTEND_URL,
};

export { env };
